// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	NodeAddr
	Command
	Operation
	LogEntry
	JoinRequest
	JoinReply
	StartRequest
	StartReply
	RequestVoteArgs
	RequestVoteReply
	AppendEntriesArgs
	AppendEntriesReply
	GetTermRequest
	GetTermReply
	GetStateRequest
	GetStateReply
	EnableNodeRequest
	EnableNodeReply
	DisableNodeRequest
	DisableNodeReply
	SetNodetoNodeRequest
	SetNodetoNodeReply
	ClientRegisterArgs
	ClientRegisterReply
	ClientRequestArgs
	ClientReply
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Raft State
type RaftState int32

const (
	RaftState_FOLLOWER  RaftState = 0
	RaftState_CANDIDATE RaftState = 1
	RaftState_LEADER    RaftState = 2
)

var RaftState_name = map[int32]string{
	0: "FOLLOWER",
	1: "CANDIDATE",
	2: "LEADER",
}
var RaftState_value = map[string]int32{
	"FOLLOWER":  0,
	"CANDIDATE": 1,
	"LEADER":    2,
}

func (x RaftState) String() string {
	return proto.EnumName(RaftState_name, int32(x))
}
func (RaftState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OpType int32

const (
	OpType_CLIENT_REGISTRATION OpType = 0
	OpType_GET                 OpType = 1
	OpType_PUT                 OpType = 2
)

var OpType_name = map[int32]string{
	0: "CLIENT_REGISTRATION",
	1: "GET",
	2: "PUT",
}
var OpType_value = map[string]int32{
	"CLIENT_REGISTRATION": 0,
	"GET": 1,
	"PUT": 2,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}
func (OpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClientReplyCode int32

const (
	ClientReplyCode_REQUEST_FAILED     ClientReplyCode = 0
	ClientReplyCode_REQUEST_SUCCESSFUL ClientReplyCode = 1
	ClientReplyCode_RETRY              ClientReplyCode = 2
	ClientReplyCode_NOT_LEADER         ClientReplyCode = 3
)

var ClientReplyCode_name = map[int32]string{
	0: "REQUEST_FAILED",
	1: "REQUEST_SUCCESSFUL",
	2: "RETRY",
	3: "NOT_LEADER",
}
var ClientReplyCode_value = map[string]int32{
	"REQUEST_FAILED":     0,
	"REQUEST_SUCCESSFUL": 1,
	"RETRY":              2,
	"NOT_LEADER":         3,
}

func (x ClientReplyCode) String() string {
	return proto.EnumName(ClientReplyCode_name, int32(x))
}
func (ClientReplyCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Node Addr
type NodeAddr struct {
	Addr string `protobuf:"bytes,1,opt,name=Addr" json:"Addr,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=Id" json:"Id,omitempty"`
}

func (m *NodeAddr) Reset()                    { *m = NodeAddr{} }
func (m *NodeAddr) String() string            { return proto.CompactTextString(m) }
func (*NodeAddr) ProtoMessage()               {}
func (*NodeAddr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeAddr) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Command struct {
	ClientId int32      `protobuf:"varint,1,opt,name=ClientId" json:"ClientId,omitempty"`
	SeqNum   uint64     `protobuf:"varint,2,opt,name=SeqNum" json:"SeqNum,omitempty"`
	Op       *Operation `protobuf:"bytes,3,opt,name=Op" json:"Op,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Command) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Command) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *Command) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

type Operation struct {
	Type  OpType `protobuf:"varint,1,opt,name=Type,enum=raft.OpType" json:"Type,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Operation) GetType() OpType {
	if m != nil {
		return m.Type
	}
	return OpType_CLIENT_REGISTRATION
}

func (m *Operation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Operation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LogEntry struct {
	Term int32    `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	Cmd  *Command `protobuf:"bytes,2,opt,name=Cmd" json:"Cmd,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogEntry) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

// Join Request
type JoinRequest struct {
	RemoteNode *NodeAddr `protobuf:"bytes,1,opt,name=RemoteNode" json:"RemoteNode,omitempty"`
	FromNode   *NodeAddr `protobuf:"bytes,2,opt,name=FromNode" json:"FromNode,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *JoinRequest) GetRemoteNode() *NodeAddr {
	if m != nil {
		return m.RemoteNode
	}
	return nil
}

func (m *JoinRequest) GetFromNode() *NodeAddr {
	if m != nil {
		return m.FromNode
	}
	return nil
}

type JoinReply struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *JoinReply) Reset()                    { *m = JoinReply{} }
func (m *JoinReply) String() string            { return proto.CompactTextString(m) }
func (*JoinReply) ProtoMessage()               {}
func (*JoinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *JoinReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Start Request
type StartRequest struct {
	RemoteNode *NodeAddr   `protobuf:"bytes,1,opt,name=RemoteNode" json:"RemoteNode,omitempty"`
	OtherNodes []*NodeAddr `protobuf:"bytes,2,rep,name=OtherNodes" json:"OtherNodes,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartRequest) GetRemoteNode() *NodeAddr {
	if m != nil {
		return m.RemoteNode
	}
	return nil
}

func (m *StartRequest) GetOtherNodes() []*NodeAddr {
	if m != nil {
		return m.OtherNodes
	}
	return nil
}

type StartReply struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *StartReply) Reset()                    { *m = StartReply{} }
func (m *StartReply) String() string            { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()               {}
func (*StartReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StartReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// RequestVoteRPC
type RequestVoteArgs struct {
	FromNode    *NodeAddr `protobuf:"bytes,1,opt,name=FromNode" json:"FromNode,omitempty"`
	Term        int32     `protobuf:"varint,2,opt,name=Term" json:"Term,omitempty"`
	CandidateId string    `protobuf:"bytes,3,opt,name=CandidateId" json:"CandidateId,omitempty"`
	LastLogIdx  int32     `protobuf:"varint,4,opt,name=LastLogIdx" json:"LastLogIdx,omitempty"`
	LastLogTerm int32     `protobuf:"varint,5,opt,name=LastLogTerm" json:"LastLogTerm,omitempty"`
}

func (m *RequestVoteArgs) Reset()                    { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()               {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RequestVoteArgs) GetFromNode() *NodeAddr {
	if m != nil {
		return m.FromNode
	}
	return nil
}

func (m *RequestVoteArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteArgs) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteArgs) GetLastLogIdx() int32 {
	if m != nil {
		return m.LastLogIdx
	}
	return 0
}

func (m *RequestVoteArgs) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	Term        int32 `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	VoteGranted bool  `protobuf:"varint,2,opt,name=VoteGranted" json:"VoteGranted,omitempty"`
}

func (m *RequestVoteReply) Reset()                    { *m = RequestVoteReply{} }
func (m *RequestVoteReply) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteReply) ProtoMessage()               {}
func (*RequestVoteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RequestVoteReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReply) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

// AppendEntriesRPC
type AppendEntriesArgs struct {
	FromNode     *NodeAddr   `protobuf:"bytes,1,opt,name=FromNode" json:"FromNode,omitempty"`
	Term         int32       `protobuf:"varint,2,opt,name=Term" json:"Term,omitempty"`
	LeaderId     string      `protobuf:"bytes,3,opt,name=LeaderId" json:"LeaderId,omitempty"`
	PrevLogIdx   int32       `protobuf:"varint,4,opt,name=PrevLogIdx" json:"PrevLogIdx,omitempty"`
	PrevLogTerm  int32       `protobuf:"varint,5,opt,name=PrevLogTerm" json:"PrevLogTerm,omitempty"`
	Entries      []*LogEntry `protobuf:"bytes,6,rep,name=Entries" json:"Entries,omitempty"`
	LeaderCommit int32       `protobuf:"varint,7,opt,name=LeaderCommit" json:"LeaderCommit,omitempty"`
}

func (m *AppendEntriesArgs) Reset()                    { *m = AppendEntriesArgs{} }
func (m *AppendEntriesArgs) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesArgs) ProtoMessage()               {}
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AppendEntriesArgs) GetFromNode() *NodeAddr {
	if m != nil {
		return m.FromNode
	}
	return nil
}

func (m *AppendEntriesArgs) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesArgs) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesArgs) GetPrevLogIdx() int32 {
	if m != nil {
		return m.PrevLogIdx
	}
	return 0
}

func (m *AppendEntriesArgs) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesArgs) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesArgs) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	Term    int32 `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
}

func (m *AppendEntriesReply) Reset()                    { *m = AppendEntriesReply{} }
func (m *AppendEntriesReply) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesReply) ProtoMessage()               {}
func (*AppendEntriesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AppendEntriesReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// GetTerm
type GetTermRequest struct {
	RemoteNode *NodeAddr `protobuf:"bytes,1,opt,name=RemoteNode" json:"RemoteNode,omitempty"`
}

func (m *GetTermRequest) Reset()                    { *m = GetTermRequest{} }
func (m *GetTermRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTermRequest) ProtoMessage()               {}
func (*GetTermRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetTermRequest) GetRemoteNode() *NodeAddr {
	if m != nil {
		return m.RemoteNode
	}
	return nil
}

type GetTermReply struct {
	Term    int32 `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
}

func (m *GetTermReply) Reset()                    { *m = GetTermReply{} }
func (m *GetTermReply) String() string            { return proto.CompactTextString(m) }
func (*GetTermReply) ProtoMessage()               {}
func (*GetTermReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetTermReply) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *GetTermReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// GetState
type GetStateRequest struct {
	RemoteNode *NodeAddr `protobuf:"bytes,1,opt,name=RemoteNode" json:"RemoteNode,omitempty"`
}

func (m *GetStateRequest) Reset()                    { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()               {}
func (*GetStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetStateRequest) GetRemoteNode() *NodeAddr {
	if m != nil {
		return m.RemoteNode
	}
	return nil
}

type GetStateReply struct {
	State   RaftState `protobuf:"varint,1,opt,name=State,enum=raft.RaftState" json:"State,omitempty"`
	Success bool      `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
}

func (m *GetStateReply) Reset()                    { *m = GetStateReply{} }
func (m *GetStateReply) String() string            { return proto.CompactTextString(m) }
func (*GetStateReply) ProtoMessage()               {}
func (*GetStateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetStateReply) GetState() RaftState {
	if m != nil {
		return m.State
	}
	return RaftState_FOLLOWER
}

func (m *GetStateReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Enable Node
type EnableNodeRequest struct {
}

func (m *EnableNodeRequest) Reset()                    { *m = EnableNodeRequest{} }
func (m *EnableNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*EnableNodeRequest) ProtoMessage()               {}
func (*EnableNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type EnableNodeReply struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *EnableNodeReply) Reset()                    { *m = EnableNodeReply{} }
func (m *EnableNodeReply) String() string            { return proto.CompactTextString(m) }
func (*EnableNodeReply) ProtoMessage()               {}
func (*EnableNodeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *EnableNodeReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Disable Node
type DisableNodeRequest struct {
}

func (m *DisableNodeRequest) Reset()                    { *m = DisableNodeRequest{} }
func (m *DisableNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DisableNodeRequest) ProtoMessage()               {}
func (*DisableNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type DisableNodeReply struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DisableNodeReply) Reset()                    { *m = DisableNodeReply{} }
func (m *DisableNodeReply) String() string            { return proto.CompactTextString(m) }
func (*DisableNodeReply) ProtoMessage()               {}
func (*DisableNodeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DisableNodeReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// SetNodetoNode
type SetNodetoNodeRequest struct {
	ToNode *NodeAddr `protobuf:"bytes,1,opt,name=ToNode" json:"ToNode,omitempty"`
	Enable bool      `protobuf:"varint,2,opt,name=Enable" json:"Enable,omitempty"`
}

func (m *SetNodetoNodeRequest) Reset()                    { *m = SetNodetoNodeRequest{} }
func (m *SetNodetoNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetNodetoNodeRequest) ProtoMessage()               {}
func (*SetNodetoNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *SetNodetoNodeRequest) GetToNode() *NodeAddr {
	if m != nil {
		return m.ToNode
	}
	return nil
}

func (m *SetNodetoNodeRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type SetNodetoNodeReply struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *SetNodetoNodeReply) Reset()                    { *m = SetNodetoNodeReply{} }
func (m *SetNodetoNodeReply) String() string            { return proto.CompactTextString(m) }
func (*SetNodetoNodeReply) ProtoMessage()               {}
func (*SetNodetoNodeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SetNodetoNodeReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Register
type ClientRegisterArgs struct {
	FromNode *NodeAddr `protobuf:"bytes,1,opt,name=FromNode" json:"FromNode,omitempty"`
}

func (m *ClientRegisterArgs) Reset()                    { *m = ClientRegisterArgs{} }
func (m *ClientRegisterArgs) String() string            { return proto.CompactTextString(m) }
func (*ClientRegisterArgs) ProtoMessage()               {}
func (*ClientRegisterArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ClientRegisterArgs) GetFromNode() *NodeAddr {
	if m != nil {
		return m.FromNode
	}
	return nil
}

type ClientRegisterReply struct {
	Code       ClientReplyCode `protobuf:"varint,1,opt,name=Code,enum=raft.ClientReplyCode" json:"Code,omitempty"`
	ClientId   int32           `protobuf:"varint,2,opt,name=ClientId" json:"ClientId,omitempty"`
	LeaderNode *NodeAddr       `protobuf:"bytes,3,opt,name=LeaderNode" json:"LeaderNode,omitempty"`
}

func (m *ClientRegisterReply) Reset()                    { *m = ClientRegisterReply{} }
func (m *ClientRegisterReply) String() string            { return proto.CompactTextString(m) }
func (*ClientRegisterReply) ProtoMessage()               {}
func (*ClientRegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ClientRegisterReply) GetCode() ClientReplyCode {
	if m != nil {
		return m.Code
	}
	return ClientReplyCode_REQUEST_FAILED
}

func (m *ClientRegisterReply) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *ClientRegisterReply) GetLeaderNode() *NodeAddr {
	if m != nil {
		return m.LeaderNode
	}
	return nil
}

// Request
type ClientRequestArgs struct {
	Cmd *Command `protobuf:"bytes,1,opt,name=Cmd" json:"Cmd,omitempty"`
}

func (m *ClientRequestArgs) Reset()                    { *m = ClientRequestArgs{} }
func (m *ClientRequestArgs) String() string            { return proto.CompactTextString(m) }
func (*ClientRequestArgs) ProtoMessage()               {}
func (*ClientRequestArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ClientRequestArgs) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type ClientReply struct {
	Code       ClientReplyCode `protobuf:"varint,1,opt,name=Code,enum=raft.ClientReplyCode" json:"Code,omitempty"`
	LeaderNode *NodeAddr       `protobuf:"bytes,2,opt,name=LeaderNode" json:"LeaderNode,omitempty"`
	Value      string          `protobuf:"bytes,3,opt,name=Value" json:"Value,omitempty"`
	SeqNum     uint64          `protobuf:"varint,4,opt,name=SeqNum" json:"SeqNum,omitempty"`
}

func (m *ClientReply) Reset()                    { *m = ClientReply{} }
func (m *ClientReply) String() string            { return proto.CompactTextString(m) }
func (*ClientReply) ProtoMessage()               {}
func (*ClientReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ClientReply) GetCode() ClientReplyCode {
	if m != nil {
		return m.Code
	}
	return ClientReplyCode_REQUEST_FAILED
}

func (m *ClientReply) GetLeaderNode() *NodeAddr {
	if m != nil {
		return m.LeaderNode
	}
	return nil
}

func (m *ClientReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ClientReply) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func init() {
	proto.RegisterType((*NodeAddr)(nil), "raft.NodeAddr")
	proto.RegisterType((*Command)(nil), "raft.Command")
	proto.RegisterType((*Operation)(nil), "raft.Operation")
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*JoinRequest)(nil), "raft.JoinRequest")
	proto.RegisterType((*JoinReply)(nil), "raft.JoinReply")
	proto.RegisterType((*StartRequest)(nil), "raft.StartRequest")
	proto.RegisterType((*StartReply)(nil), "raft.StartReply")
	proto.RegisterType((*RequestVoteArgs)(nil), "raft.RequestVoteArgs")
	proto.RegisterType((*RequestVoteReply)(nil), "raft.RequestVoteReply")
	proto.RegisterType((*AppendEntriesArgs)(nil), "raft.AppendEntriesArgs")
	proto.RegisterType((*AppendEntriesReply)(nil), "raft.AppendEntriesReply")
	proto.RegisterType((*GetTermRequest)(nil), "raft.GetTermRequest")
	proto.RegisterType((*GetTermReply)(nil), "raft.GetTermReply")
	proto.RegisterType((*GetStateRequest)(nil), "raft.GetStateRequest")
	proto.RegisterType((*GetStateReply)(nil), "raft.GetStateReply")
	proto.RegisterType((*EnableNodeRequest)(nil), "raft.EnableNodeRequest")
	proto.RegisterType((*EnableNodeReply)(nil), "raft.EnableNodeReply")
	proto.RegisterType((*DisableNodeRequest)(nil), "raft.DisableNodeRequest")
	proto.RegisterType((*DisableNodeReply)(nil), "raft.DisableNodeReply")
	proto.RegisterType((*SetNodetoNodeRequest)(nil), "raft.SetNodetoNodeRequest")
	proto.RegisterType((*SetNodetoNodeReply)(nil), "raft.SetNodetoNodeReply")
	proto.RegisterType((*ClientRegisterArgs)(nil), "raft.ClientRegisterArgs")
	proto.RegisterType((*ClientRegisterReply)(nil), "raft.ClientRegisterReply")
	proto.RegisterType((*ClientRequestArgs)(nil), "raft.ClientRequestArgs")
	proto.RegisterType((*ClientReply)(nil), "raft.ClientReply")
	proto.RegisterEnum("raft.RaftState", RaftState_name, RaftState_value)
	proto.RegisterEnum("raft.OpType", OpType_name, OpType_value)
	proto.RegisterEnum("raft.ClientReplyCode", ClientReplyCode_name, ClientReplyCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RaftRPC service

type RaftRPCClient interface {
	JoinRPC(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error)
	StartRPC(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	RequestVoteRPC(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error)
	AppendEntriesRPC(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesReply, error)
	ClientRequestRPC(ctx context.Context, in *ClientRequestArgs, opts ...grpc.CallOption) (*ClientReply, error)
	ClientRegisterRequestRPC(ctx context.Context, in *ClientRegisterArgs, opts ...grpc.CallOption) (*ClientRegisterReply, error)
	GetTermRPC(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*GetTermReply, error)
	GetStateRPC(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateReply, error)
	EnableNodeRPC(ctx context.Context, in *EnableNodeRequest, opts ...grpc.CallOption) (*EnableNodeReply, error)
	DisableNodeRPC(ctx context.Context, in *DisableNodeRequest, opts ...grpc.CallOption) (*DisableNodeReply, error)
	SetNodetoNodeRPC(ctx context.Context, in *SetNodetoNodeRequest, opts ...grpc.CallOption) (*SetNodetoNodeReply, error)
}

type raftRPCClient struct {
	cc *grpc.ClientConn
}

func NewRaftRPCClient(cc *grpc.ClientConn) RaftRPCClient {
	return &raftRPCClient{cc}
}

func (c *raftRPCClient) JoinRPC(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/JoinRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) StartRPC(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/StartRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) RequestVoteRPC(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error) {
	out := new(RequestVoteReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/RequestVoteRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) AppendEntriesRPC(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesReply, error) {
	out := new(AppendEntriesReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/AppendEntriesRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) ClientRequestRPC(ctx context.Context, in *ClientRequestArgs, opts ...grpc.CallOption) (*ClientReply, error) {
	out := new(ClientReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/ClientRequestRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) ClientRegisterRequestRPC(ctx context.Context, in *ClientRegisterArgs, opts ...grpc.CallOption) (*ClientRegisterReply, error) {
	out := new(ClientRegisterReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/ClientRegisterRequestRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) GetTermRPC(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*GetTermReply, error) {
	out := new(GetTermReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/GetTermRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) GetStateRPC(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateReply, error) {
	out := new(GetStateReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/GetStateRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) EnableNodeRPC(ctx context.Context, in *EnableNodeRequest, opts ...grpc.CallOption) (*EnableNodeReply, error) {
	out := new(EnableNodeReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/EnableNodeRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) DisableNodeRPC(ctx context.Context, in *DisableNodeRequest, opts ...grpc.CallOption) (*DisableNodeReply, error) {
	out := new(DisableNodeReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/DisableNodeRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) SetNodetoNodeRPC(ctx context.Context, in *SetNodetoNodeRequest, opts ...grpc.CallOption) (*SetNodetoNodeReply, error) {
	out := new(SetNodetoNodeReply)
	err := grpc.Invoke(ctx, "/raft.RaftRPC/SetNodetoNodeRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RaftRPC service

type RaftRPCServer interface {
	JoinRPC(context.Context, *JoinRequest) (*JoinReply, error)
	StartRPC(context.Context, *StartRequest) (*StartReply, error)
	RequestVoteRPC(context.Context, *RequestVoteArgs) (*RequestVoteReply, error)
	AppendEntriesRPC(context.Context, *AppendEntriesArgs) (*AppendEntriesReply, error)
	ClientRequestRPC(context.Context, *ClientRequestArgs) (*ClientReply, error)
	ClientRegisterRequestRPC(context.Context, *ClientRegisterArgs) (*ClientRegisterReply, error)
	GetTermRPC(context.Context, *GetTermRequest) (*GetTermReply, error)
	GetStateRPC(context.Context, *GetStateRequest) (*GetStateReply, error)
	EnableNodeRPC(context.Context, *EnableNodeRequest) (*EnableNodeReply, error)
	DisableNodeRPC(context.Context, *DisableNodeRequest) (*DisableNodeReply, error)
	SetNodetoNodeRPC(context.Context, *SetNodetoNodeRequest) (*SetNodetoNodeReply, error)
}

func RegisterRaftRPCServer(s *grpc.Server, srv RaftRPCServer) {
	s.RegisterService(&_RaftRPC_serviceDesc, srv)
}

func _RaftRPC_JoinRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).JoinRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/JoinRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).JoinRPC(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_StartRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).StartRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/StartRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).StartRPC(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_RequestVoteRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).RequestVoteRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/RequestVoteRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).RequestVoteRPC(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_AppendEntriesRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).AppendEntriesRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/AppendEntriesRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).AppendEntriesRPC(ctx, req.(*AppendEntriesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_ClientRequestRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).ClientRequestRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/ClientRequestRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).ClientRequestRPC(ctx, req.(*ClientRequestArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_ClientRegisterRequestRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRegisterArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).ClientRegisterRequestRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/ClientRegisterRequestRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).ClientRegisterRequestRPC(ctx, req.(*ClientRegisterArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_GetTermRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).GetTermRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/GetTermRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).GetTermRPC(ctx, req.(*GetTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_GetStateRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).GetStateRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/GetStateRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).GetStateRPC(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_EnableNodeRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).EnableNodeRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/EnableNodeRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).EnableNodeRPC(ctx, req.(*EnableNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_DisableNodeRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).DisableNodeRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/DisableNodeRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).DisableNodeRPC(ctx, req.(*DisableNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_SetNodetoNodeRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodetoNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).SetNodetoNodeRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/SetNodetoNodeRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).SetNodetoNodeRPC(ctx, req.(*SetNodetoNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftRPC",
	HandlerType: (*RaftRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRPC",
			Handler:    _RaftRPC_JoinRPC_Handler,
		},
		{
			MethodName: "StartRPC",
			Handler:    _RaftRPC_StartRPC_Handler,
		},
		{
			MethodName: "RequestVoteRPC",
			Handler:    _RaftRPC_RequestVoteRPC_Handler,
		},
		{
			MethodName: "AppendEntriesRPC",
			Handler:    _RaftRPC_AppendEntriesRPC_Handler,
		},
		{
			MethodName: "ClientRequestRPC",
			Handler:    _RaftRPC_ClientRequestRPC_Handler,
		},
		{
			MethodName: "ClientRegisterRequestRPC",
			Handler:    _RaftRPC_ClientRegisterRequestRPC_Handler,
		},
		{
			MethodName: "GetTermRPC",
			Handler:    _RaftRPC_GetTermRPC_Handler,
		},
		{
			MethodName: "GetStateRPC",
			Handler:    _RaftRPC_GetStateRPC_Handler,
		},
		{
			MethodName: "EnableNodeRPC",
			Handler:    _RaftRPC_EnableNodeRPC_Handler,
		},
		{
			MethodName: "DisableNodeRPC",
			Handler:    _RaftRPC_DisableNodeRPC_Handler,
		},
		{
			MethodName: "SetNodetoNodeRPC",
			Handler:    _RaftRPC_SetNodetoNodeRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1088 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x6e, 0xfe, 0x93, 0x93, 0x36, 0x71, 0xa7, 0xdd, 0xae, 0xf1, 0x05, 0x54, 0x96, 0x76, 0xb5,
	0x14, 0x54, 0xa4, 0xec, 0x5e, 0x20, 0x81, 0x44, 0xdd, 0xc4, 0x2d, 0x59, 0xa2, 0x24, 0x3b, 0x71,
	0x0a, 0xdc, 0x50, 0x79, 0x37, 0x43, 0x89, 0xd4, 0xc4, 0x59, 0xc7, 0x45, 0xf4, 0x1d, 0xb8, 0xe6,
	0x4d, 0x78, 0x1a, 0x1e, 0x06, 0xce, 0xfc, 0xd8, 0x19, 0x3b, 0xd9, 0xa0, 0x56, 0x7b, 0xd3, 0xce,
	0x9c, 0x9f, 0x6f, 0xbe, 0x73, 0xe6, 0xcc, 0x39, 0x31, 0x40, 0xe8, 0xff, 0x1a, 0x9d, 0x2e, 0xc2,
	0x20, 0x0a, 0x48, 0x91, 0xaf, 0xed, 0x53, 0xa8, 0xf6, 0x83, 0x09, 0x73, 0x26, 0x93, 0x90, 0x10,
	0x28, 0xf2, 0xff, 0x66, 0xee, 0x38, 0xf7, 0xa2, 0x46, 0xc5, 0x9a, 0x34, 0x20, 0xdf, 0x9d, 0x98,
	0x79, 0x21, 0xc1, 0x95, 0xfd, 0x0b, 0x54, 0xda, 0xc1, 0x6c, 0xe6, 0xcf, 0x27, 0xc4, 0x82, 0x6a,
	0xfb, 0x76, 0xca, 0xe6, 0x11, 0x1a, 0x70, 0x97, 0x12, 0x4d, 0xf6, 0xe4, 0x08, 0xca, 0x23, 0xf6,
	0xbe, 0x7f, 0x37, 0x13, 0xae, 0x45, 0xaa, 0x76, 0xe4, 0x33, 0xc8, 0x0f, 0x16, 0x66, 0x01, 0x65,
	0xf5, 0x56, 0xf3, 0x54, 0xb0, 0x19, 0x2c, 0x58, 0xe8, 0x47, 0xd3, 0x60, 0x4e, 0x51, 0x65, 0x8f,
	0xa1, 0x96, 0x08, 0xc8, 0x31, 0x14, 0xbd, 0xfb, 0x05, 0x13, 0xe8, 0x8d, 0xd6, 0x6e, 0x6c, 0xcf,
	0x65, 0x54, 0x68, 0x88, 0x01, 0x85, 0x1f, 0xd8, 0xbd, 0xe2, 0xc7, 0x97, 0xe4, 0x10, 0x4a, 0x57,
	0xfe, 0xed, 0x1d, 0x13, 0x87, 0xd4, 0xa8, 0xdc, 0xd8, 0xdf, 0x41, 0xb5, 0x17, 0xdc, 0xb8, 0xf3,
	0x28, 0xbc, 0xe7, 0x61, 0x7a, 0x2c, 0x9c, 0x29, 0xce, 0x62, 0x8d, 0xbc, 0x0a, 0xed, 0x99, 0x8c,
	0xb3, 0xde, 0xda, 0x93, 0x07, 0xa9, 0x38, 0x29, 0xd7, 0xd8, 0x53, 0xa8, 0xbf, 0x0e, 0xa6, 0x73,
	0xca, 0xde, 0xdf, 0xb1, 0x65, 0x44, 0x4e, 0x01, 0x28, 0x9b, 0x05, 0x11, 0xe3, 0xc9, 0x13, 0x48,
	0xf5, 0x56, 0x43, 0xba, 0xc5, 0xe9, 0xa4, 0x9a, 0x05, 0x39, 0x81, 0xea, 0x45, 0x18, 0xcc, 0x84,
	0x75, 0x7e, 0xa3, 0x75, 0xa2, 0xb7, 0x9f, 0x41, 0x4d, 0x1e, 0xb5, 0xb8, 0xbd, 0x27, 0x26, 0x54,
	0x46, 0x77, 0xef, 0xde, 0xb1, 0xe5, 0x52, 0x9c, 0x52, 0xa5, 0xf1, 0xd6, 0x9e, 0xc3, 0xee, 0x28,
	0xf2, 0xc3, 0xe8, 0xb1, 0x94, 0xd0, 0x7e, 0x10, 0xfd, 0xc6, 0x42, 0xbe, 0x59, 0x22, 0xa9, 0xc2,
	0x26, 0xfb, 0x95, 0x85, 0xfd, 0x1c, 0x40, 0x9d, 0xb7, 0x9d, 0xd7, 0xdf, 0x39, 0x68, 0x2a, 0x4e,
	0x57, 0x78, 0x96, 0x13, 0xde, 0x2c, 0x53, 0xe1, 0xe7, 0xb6, 0x87, 0x9f, 0x5c, 0x4f, 0x5e, 0xbb,
	0x9e, 0x63, 0xa8, 0xb7, 0xf1, 0x2a, 0xa6, 0x13, 0x3f, 0x62, 0x58, 0x6d, 0xf2, 0x6a, 0x75, 0x11,
	0xf9, 0x14, 0xa0, 0xe7, 0x2f, 0x23, 0xbc, 0xe4, 0xee, 0xe4, 0x0f, 0xb3, 0x28, 0x7c, 0x35, 0x09,
	0x47, 0x50, 0x3b, 0x01, 0x5e, 0x12, 0x06, 0xba, 0xc8, 0xfe, 0x1e, 0x0c, 0x8d, 0xb6, 0x8c, 0x72,
	0x53, 0xa9, 0x20, 0x12, 0x37, 0xb8, 0x0c, 0xfd, 0x79, 0xc4, 0x64, 0xc9, 0x54, 0xa9, 0x2e, 0xb2,
	0xff, 0xcd, 0xc1, 0xbe, 0xb3, 0x58, 0xb0, 0xf9, 0x84, 0x17, 0xdc, 0x94, 0x2d, 0x3f, 0x4a, 0x0e,
	0xf0, 0xb9, 0xf5, 0x98, 0x3f, 0x61, 0x61, 0x92, 0x80, 0x64, 0xcf, 0xa3, 0x1f, 0x86, 0xec, 0xf7,
	0x74, 0xf4, 0x2b, 0x09, 0xe7, 0xac, 0x76, 0x7a, 0xf4, 0x9a, 0x88, 0xbc, 0x80, 0x8a, 0x22, 0x6b,
	0x96, 0xf5, 0x52, 0x88, 0x5f, 0x0d, 0x8d, 0xd5, 0xc4, 0x86, 0x5d, 0x79, 0x2e, 0x7f, 0x1f, 0xd3,
	0xc8, 0xac, 0x08, 0xb0, 0x94, 0xcc, 0x3e, 0x07, 0x92, 0x4a, 0xc0, 0x87, 0xb3, 0xa9, 0xd5, 0x51,
	0x3e, 0x5d, 0x47, 0x67, 0xd0, 0xb8, 0x64, 0x11, 0x37, 0x7a, 0x64, 0x85, 0xdb, 0xdf, 0xc2, 0x6e,
	0x82, 0xf0, 0xf0, 0xf3, 0x1d, 0x68, 0xa2, 0x37, 0x96, 0x3c, 0x2f, 0x86, 0xc7, 0x11, 0x18, 0xc2,
	0xde, 0x0a, 0x82, 0x33, 0x78, 0x06, 0x25, 0xb1, 0x53, 0x1d, 0x4d, 0x75, 0x40, 0x8a, 0x7f, 0xa4,
	0x91, 0xd4, 0x6e, 0x21, 0x75, 0x00, 0xfb, 0xee, 0xdc, 0x7f, 0x7b, 0x2b, 0xf0, 0x15, 0x2d, 0xfb,
	0x0b, 0x68, 0xea, 0xc2, 0xed, 0xcf, 0xf3, 0x10, 0x48, 0x67, 0xba, 0xcc, 0x42, 0x7c, 0x09, 0x46,
	0x4a, 0xba, 0x1d, 0xe3, 0x0a, 0x0e, 0x47, 0x2c, 0xe2, 0x96, 0x51, 0xa0, 0xa1, 0x90, 0xe7, 0x50,
	0xf6, 0x82, 0x2d, 0xb9, 0x51, 0x5a, 0x3e, 0x1d, 0x24, 0x61, 0x15, 0x9e, 0xda, 0xe1, 0x30, 0x22,
	0x19, 0xdc, 0xed, 0x3c, 0xce, 0x80, 0xc8, 0x89, 0x43, 0xd9, 0xcd, 0x74, 0x19, 0xb1, 0xf0, 0xa1,
	0x0f, 0xcd, 0xfe, 0x33, 0x07, 0x07, 0x69, 0x08, 0x79, 0xe6, 0xe7, 0x50, 0x6c, 0xc7, 0xfe, 0x8d,
	0xd6, 0x13, 0x35, 0x10, 0x94, 0x21, 0x1a, 0x70, 0x25, 0x15, 0x26, 0xa9, 0x31, 0x98, 0xcf, 0x8c,
	0x41, 0x2c, 0x18, 0xf9, 0x2e, 0x04, 0x99, 0xc2, 0xe6, 0x82, 0x59, 0x59, 0xd8, 0xaf, 0x60, 0x3f,
	0x3e, 0x44, 0x64, 0x54, 0xc4, 0xa3, 0x66, 0x53, 0xee, 0x83, 0xb3, 0xe9, 0xaf, 0x1c, 0xb6, 0xc7,
	0x15, 0xb7, 0x87, 0x90, 0x4f, 0x13, 0xcc, 0xff, 0x1f, 0xc1, 0xcd, 0xd3, 0x55, 0x9b, 0xf6, 0x45,
	0x7d, 0xda, 0x9f, 0xbc, 0x82, 0x5a, 0x52, 0xdb, 0x64, 0x17, 0xaf, 0x65, 0xd0, 0xeb, 0x0d, 0x7e,
	0x74, 0xa9, 0xb1, 0x43, 0xf6, 0xa0, 0xd6, 0x76, 0xfa, 0x9d, 0x6e, 0xc7, 0xf1, 0x5c, 0x23, 0x47,
	0x00, 0xca, 0x3d, 0xd7, 0xe9, 0xa0, 0x2a, 0x7f, 0xf2, 0x12, 0xca, 0x72, 0xc6, 0x93, 0xa7, 0x78,
	0x39, 0xbd, 0xae, 0xdb, 0xf7, 0xae, 0xa9, 0x7b, 0xd9, 0x1d, 0x79, 0xd4, 0xf1, 0xba, 0x83, 0x3e,
	0x7a, 0x57, 0xa0, 0x70, 0xe9, 0x7a, 0xe8, 0x87, 0x8b, 0xe1, 0xd8, 0x43, 0xa7, 0x9f, 0xa0, 0x99,
	0x89, 0x10, 0x9f, 0x7b, 0x83, 0xba, 0x6f, 0xc6, 0xee, 0xc8, 0xbb, 0xbe, 0x70, 0xba, 0x3d, 0xb7,
	0x83, 0x8e, 0x47, 0x40, 0x62, 0xd9, 0x68, 0xdc, 0x6e, 0xbb, 0xa3, 0xd1, 0xc5, 0xb8, 0x87, 0x38,
	0x35, 0x28, 0x51, 0xd7, 0xa3, 0x3f, 0x1b, 0x79, 0xfc, 0xc5, 0x03, 0xfd, 0x81, 0x77, 0xad, 0xe8,
	0x14, 0x5a, 0xff, 0x94, 0xa0, 0xc2, 0xa3, 0xa0, 0xc3, 0x36, 0xf9, 0x0a, 0x2a, 0x62, 0x34, 0xe3,
	0x72, 0x5f, 0x66, 0x49, 0xfb, 0x51, 0x60, 0x35, 0x75, 0x11, 0xb2, 0xb0, 0x77, 0x48, 0x0b, 0xaa,
	0x72, 0x68, 0xa2, 0x07, 0x91, 0x6a, 0x7d, 0x68, 0x5b, 0x46, 0x4a, 0x26, 0x7d, 0x1c, 0xe4, 0xad,
	0x0d, 0x22, 0xf4, 0x54, 0x57, 0x98, 0x99, 0xaa, 0xd6, 0xd1, 0x9a, 0x38, 0x86, 0xb8, 0x04, 0x23,
	0xdd, 0x7f, 0x11, 0xe4, 0xa9, 0xb4, 0x5e, 0x1b, 0x4c, 0x96, 0xb9, 0x41, 0x11, 0x03, 0x9d, 0x81,
	0x91, 0x2a, 0x48, 0x0d, 0x68, 0xad, 0x50, 0xad, 0xfd, 0xb5, 0x4a, 0x43, 0x84, 0x37, 0x60, 0x66,
	0x1f, 0x58, 0x82, 0x64, 0xa6, 0x1d, 0x56, 0x6f, 0xd8, 0xfa, 0x64, 0x93, 0x26, 0x86, 0xfc, 0x1a,
	0x20, 0xee, 0xeb, 0x08, 0x72, 0x28, 0x4d, 0xd3, 0xb3, 0xc2, 0x22, 0x19, 0xa9, 0xf4, 0xfc, 0x06,
	0xea, 0x49, 0x43, 0x5e, 0xe5, 0x35, 0xd3, 0xe6, 0xad, 0x83, 0xac, 0x38, 0xbe, 0x97, 0x3d, 0xad,
	0xcd, 0xae, 0x12, 0xb1, 0xd6, 0x90, 0xad, 0x27, 0xeb, 0x0a, 0x09, 0xd1, 0x81, 0x86, 0xde, 0x66,
	0x57, 0x29, 0x58, 0x6f, 0xc9, 0xf1, 0xed, 0x66, 0xdb, 0x32, 0xa2, 0xbc, 0x06, 0x23, 0xdd, 0x26,
	0x11, 0xc7, 0x52, 0x85, 0xb4, 0xa1, 0x2d, 0xc7, 0x17, 0xbc, 0xde, 0x5a, 0xed, 0x9d, 0xf3, 0x03,
	0x10, 0xdf, 0x01, 0xe7, 0x35, 0xfe, 0x77, 0xc8, 0x3f, 0x0c, 0x86, 0xb9, 0xb7, 0x65, 0xf1, 0x85,
	0xf0, 0xf2, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xa9, 0xe5, 0xbe, 0x2f, 0x0c, 0x00, 0x00,
}
